### PR TITLE
Update README with unlisted step after restart

### PR DESCRIPTION
**Pull request by marshyski**
Had to re-run unrestricted after restart. Thank you for the script, will test and let you know if any adjustments need to be made. I would like to update my gist with your script if that is okay? https://gist.github.com/marshyski/899bce1b6da3f30920297e7bddbb5580

### CODE REVIEW

**Comment by djdallmann** [comment]
Feel free to reference my script on your gist, I noticed you reference ChefKoch on your gist his github was taken down a while ago for plagiarism if I recall.

As for the unrestricted part that seems odd, I've used this process on 30-40 builds and never had an issue. I think you might have a conflicting build, tool or process. If you can provide more detail about your build I could try replicating or isolating cause.

**Comment by marshyski** [comment]
Thank you! Yes, you're right about ChefKoch, I'm going to clean up my gist in the coming month or so. Trying to make it dummy proof.

I only had to re-run unrestricted after the reboot. When I ran the reboot and ran the script without running step 6 I got errors in my console. I'm sorry I did not save the output, but recommendation to add logging to the GamingPCSetup directory.

Thank you for taking the time to investigate this.

Here is my system information.

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-L9MIB96
System Manufacturer	Micro-Star International Co., Ltd.
System Model	GS66 Stealth 10SFS
System Type	x64-based PC
System SKU	16V1.1
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. E16V1IMS.110, 9/23/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	MS-16V1
BaseBoard Version	REV:1.0
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.488"
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.8 GB
Available Physical Memory	24.1 GB
Total Virtual Memory	36.8 GB
Available Virtual Memory	26.4 GB
Page File Space	5.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
```

**Comment by djdallmann** [comment]
Windows has logs for powershell and powershell DSC, 
event viewer > applications and services log > windows > Powershell and Powershell Desired State Configuration.  The only error I can think of is that Windows Remote Management service didn't start immediately after boot which is needed for powershell DSC to work.

**Comment by marshyski** [comment]
That would make a lot of sense as it's a delayed start and I did run it pretty quick after reboot. I only saw a couple of errors in DSC logs, please see below. You're welcome to close PR since I have fast fingers :-D

```csv
Level,Date and Time,Source,Event ID,Task Category
Error,12/12/2020 1:08:54 AM,Microsoft-Windows-DSC,4252,None,"Job {7DF1C694-3C40-11EB-925A-D83BBFE6EBFE} : 
MIResult: 1
Error Message: Cannot invoke the Start-DscConfiguration cmdlet. The Consistency Check or Pull cmdlet is in progress and must return before Start-DscConfiguration can be invoked. Use -Force option if that is available to cancel the current operation.
Message ID: MI RESULT 1
Error Category: 0
Error Code: 1
Error Type: MI"
Error,12/12/2020 1:06:02 AM,Microsoft-Windows-DSC,4252,None,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
MIResult: 1
Error Message: The SendConfigurationApply function did not succeed.
Message ID: MI RESULT 1
Error Category: 0
Error Code: 1
Error Type: MI"
Error,12/12/2020 1:05:54 AM,Microsoft-Windows-DSC,4252,None,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: Service 'Touch Keyboard and Handwriting Panel Service (TabletInputService)' cannot be stopped due to the following error: Cannot stop TabletInputService service on computer '.'. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI"
Error,12/12/2020 1:05:54 AM,Microsoft-Windows-DSC,4097,Send configuration scenario for Local configuration manager,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [Service]SvcTabletInputService and Source Info is C:\Users\Bingo\Documents\GameSetup.ps1::657::9::Service. Error Message is PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: Service 'Touch Keyboard and Handwriting Panel Service (TabletInputService)' cannot be stopped due to the following error: Cannot stop TabletInputService service on computer '.'. ."
Error,12/12/2020 1:05:54 AM,Microsoft-Windows-DSC,4250,None,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
Message Service 'Touch Keyboard and Handwriting Panel Service (TabletInputService)' cannot be stopped due to the following error: Cannot stop TabletInputService service on computer '.'. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)"
Error,12/12/2020 1:05:49 AM,Microsoft-Windows-DSC,4252,None,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: Service 'Radio Management Service (RmSvc)' stop failed. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI"
Error,12/12/2020 1:05:49 AM,Microsoft-Windows-DSC,4097,Send configuration scenario for Local configuration manager,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [Service]SvcRmSvc and Source Info is C:\Users\Bingo\Documents\GameSetup.ps1::607::9::Service. Error Message is PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: Service 'Radio Management Service (RmSvc)' stop failed. ."
Error,12/12/2020 1:05:49 AM,Microsoft-Windows-DSC,4250,None,"Job {089483F2-3C40-11EB-9259-D83BBFE6EBFE} : 
Message Service 'Radio Management Service (RmSvc)' stop failed. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)"
```

**Comment by djdallmann** [comment]
Thanks for the feedback, going to close this off.

**Pull request closed without merging**
