### PR TITLE
Aelius tweaks

### PR DESCRIPTION
**Pull request by AeliusSaionji**
I've followed this guide and hit a few problems along the way- I've also some insight to contribute.

I've included here the low hanging fruit, but for my other suggestions I think we'd need a place to discuss how to make the changes.

For example, the guide suggests disabling GameMode, as well as SpeedShift and SpeedStep.

But this is dubious advice. Some of the sources linked explicitly advise against this.
Moreover, GameMode overrides them and pins the processor to its max frequency when a game is detected. GameMode also inhibits various services from running (indexer, windows update). Not having GameMode is a detriment in of itself, and having GameMode eliminates the potential benefit of disabling SST and EIST.

Additionally, it is suggested in the BIOS guide to disable RGB, but no reason is given for this. What performance implications does RGB have? I would be fascinated to learn about that, and it would be prudent to link the sources for this claim so others may learn about it as well.

But if no benefit exists, then the suggestion does not belong in the guide.

Thanks for the work thus far

### CODE REVIEW

**Comment by amitxv** [comment]
[Running a RGB effect/animation can take a great toll on the MCU. It requires a lot of processing power and will delay other processes.](https://next.wooting.io/post/what-influences-keyboard-speed)

**Comment by AeliusSaionji** [comment]
It seems plausible for a keyboard using one MCU to share data transfer and run this logic, but can you demonstrate that a motherboard is sharing resources to run its RGB?

**Comment by amitxv** [comment]
The same logic can be applied to a motherboard in the sense that unnecessary power will be drawn which may lead to increased heat output and EMI. Although it may be minuscule, there are many people that prefer to avoid this nuisance when tuning their system.

**Comment by AeliusSaionji** [comment]
The premise for this guide is evidence-based facts, not unsubstantiated potential maybes.

**Comment by AeliusSaionji** [comment]
I edited my previous response to be less grumpy.

For context, what motivated me to read and contribute to this guide is exactly the evidence based nature of it.

Plausibly beneficial changes are functionally superstition, and superstition can snowball into pure pseudoscience. See the audiophile community, and most "increase fps" discussions found on reddit and youtube.

Sticking to what can be demonstrated is a worthy goal.

**Comment by djdallmann** [comment]
Thanks for the feedback so far and AMIT for commenting.

Disabling RGB 
- RGB and related power sources have been known to cause audio interference but it "depends". Then there's situations like Corsair iCUE which previously required their software to be running all the time to control it, less software running the better. I'd be ok with stating something along those lines that "you may enable RGB after all optimizations and testing have been complete, then test again for impacts to your benchmarks and experience". Generally the fewer the variables the better.

Flow Control
- Works similarly to TCP Window Size by notifying a transmitter to reduce or to delay sending data being sent, it requests a system to buffer data temporarily until congestion is reduced or the receiver can allow it. There's other things at play here as well to handle congestion built into operating systems and routers.
- Intel recommends disabling Flow Control here but indicates you could drop packets as a result, likely under extreme load.
  - https://www.intel.com/content/www/us/en/support/articles/000005811/ethernet-products.html
- https://blog.cloudflare.com/how-to-achieve-low-latency/ 
  - "flow control [...] it can introduce unpredictable latency spikes during higher load"
- Many games rely on UDP which is a connectionless protocol, send and hope it gets there. No guarantees anyways.
- When playing competitively ideal conditions would be playing on an unsaturated local network over the internet. Turn off other network devices for best case for localized variables. QoS or packet priority scheduling algorithms can help with higher throughput networks if you have no control of network usage. fq_codel, cake etc. Bufferbloat problem.
- For Flow Control to work, connected routers, and devices must also support it and have it enabled.

NVIDIA Recommendations
- I'll review more closely but could be reasonable to update it as suggested. No ETA right now.

SpeedShift and SpeedStep (EIST)
- These are power saving and efficiency features to manage voltage and frequency based on workload, one implemented in hardware the other software.
- Typically the concern here is transition times between those states could impact performance in comparison to a static voltage and frequency configuration.
- "Some of the sources linked explicitly advise against this" feel free to provide reference and refresh my memory.

GameMode
- It has some benefits but often those benefits are taken care of by careful optimizations, disabling windows updates and background processes which may also cause notifications. 
- You can use Windows Performance Recorder and Analyzer to see when GameMode is engaged, I haven't done much testing around it personally but it seems more useful for casual gamers than competitive with optimized systems. Feel free to add more context if you have some references.

Steam Path Anti-Virus Exclusion
- Thanks, yes pros and cons to this one, I can revisit.

**Review by djdallmann — APPROVED** [review]

**Review by djdallmann — APPROVED** [review]

**Review by djdallmann — COMMENTED** [review]
I'm going to reword this one to say there can be impacts etc

**Comment by AeliusSaionji** [comment]
> I haven't done much testing around [Game Mode] personally but it seems more useful for casual gamers than competitive with optimized systems

I have indeed been approaching this as more of an end user, I definitely agree that a specific purpose use machine doesn't need to keep EIST and SST enabled. I also don't have further specifics of what game mode does at this time, and agree that it represents potential behavioral uncertainty, particularly as updates change its behavior in the future.

**Review by djdallmann — CHANGES_REQUESTED** [review]
What about something like this?

     * Disabling this can cause dropped frames in some situations which can reduce throughput if a link partner cannot sustain the data transfer rate, link partners must support flow control frames for the feature to work.
     * See Technical Reference: Tuning Throughput Performance for Intel® Ethernet Adapters.

**Comment by AeliusSaionji** [comment]
For some reason at the time I wrote the commit I generalized "streaming video".

The specific impact that I observed was to game streaming, which I make use of over LAN. I recognize that the guide recommends disabling this in Steam.

I use Sunshine Game Stream (the foss replacement server to nvidia gamestream) and Moonlight as my client. With flow control disabled on the host, packet loss was so high no stream could be transmitted, unless I restricted the bitrate such that bandwidth did not exceed 5mbps.

I suspect this would also impact streaming from OBS to twitch or youtube or other.

**Comment by djdallmann** [comment]
> I use Sunshine Game Stream (the foss replacement server to nvidia gamestream) and Moonlight as my client. With flow control disabled on the host, packet loss was so high no stream could be transmitted, unless I restricted the bitrate such that bandwidth did not exceed 5mbps.

Thanks for adding context! Btw can you tell me more about your network, ISP up/down speed, any QoS (in Windows/Router etc?), are all systems involved 1000Gbps? Do you have double NAT, Internet <-> ISP (NAT) <-> Personal Router (NAT) <-> Desktops?

**Comment by AeliusSaionji** [comment]
I (near) exclusively stream in-LAN, using it primarily as an RDP alternative.

My typical bandwidth needs are 20mbps, and the host PC is wired but the clients are often wireless.

I observed the issue from two laptops and my phone, and I do not have QoS enabled on any computer or the router, which is an Edgerouter X paired with U6-IW.

Keeping in mind the problem was a direct connection over (W)LAN, and Flow Control off unambiguously led to a severe and un-ignorible plummet in performance:

I have 300mbps down, 50mbps up, conventional single NAT, and the host PC is regrettably on a 100mbps link.

**Comment by djdallmann** [comment]
> What about something like this?
> 
> ```
>  * Disabling this can cause dropped frames in some situations which can reduce throughput if a link partner cannot sustain the data transfer rate, link partners must support flow control frames for the feature to work.
>  * See Technical Reference: Tuning Throughput Performance for Intel® Ethernet Adapters.
> ```

@AeliusSaionji just looking for final changes on this, see recommendation ^. Once we're good I can finalize the full pull or I can pull the other two short term.

**Comment by AeliusSaionji** [comment]
> Disabling this can cause dropped frames in some situations which can reduce throughput if a link partner cannot sustain the data transfer rate, link partners must support flow control frames for the feature to work.

I think the way this reads is confusing, because you transition from speaking about the disabled state to speaking about the enabled state (?) rather subtly. Drawing more attention to the state we're referring to would make it more clear:

- Disabling can cause...
- When enabled, partners must also support...

I do also thing it's worth explicitly stating that "some situations" includes "live streaming and remote access". There's a lot this _could_ impact, but it would be broadly useful to give an example of what kind of traffic is _definitely_ affected, and how severely.
Live streaming and (moonlight) remote access are also gaming adjacent activities; the incompatibility is something many will probably want to know.

How about this?

```text
* Disabling this can cause dropped frames in some situations, reducing throughput
if a link partner cannot sustain the data transfer rate. In particular, video
streaming may become untenable.

* If enabled, only link partners supporting flow control frames will benefit.

* See Technical Reference: Tuning Throughput Performance for Intel® Ethernet
Adapters
```

**Comment by djdallmann** [comment]
Works for me :D

**Comment by djdallmann** [comment]
@AeliusSaionji just make those changes to your pull request and I'll accept.

**Review by djdallmann — APPROVED** [review]

**Review by djdallmann — APPROVED** [review]

**Pull request merged**
